name: Basic Verifications

on:
  push:
    branches: [main, develop]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  basic-verifications:
    name: Verify code format and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify code and apply tests
        run: ./mvnw verify
